[project]
name = "rt-voice-spark-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.3.1",
    "llama-cpp-python>=0.3.16",
]
